using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// [MANDATORY] The following GUID is used as a unique identifier of the plugin. Generate a fresh one for your plugin!
[assembly: Guid("6bc21e30-740c-465f-a4fa-efe7e793f3d6")]

// [MANDATORY] The assembly versioning
//Should be incremented for each new release build of a plugin
[assembly: AssemblyVersion("1.2.1.0")]
[assembly: AssemblyFileVersion("1.2.1.0")]

// [MANDATORY] The name of your plugin
[assembly: AssemblyTitle("NightFront")]
// [MANDATORY] A short description of your plugin
[assembly: AssemblyDescription("Sync and execute plans developed with NightFront app")]

// The following attributes are not required for the plugin per se, but are required by the official manifest meta data

// Your name
[assembly: AssemblyCompany("Jeff Ridder")]
// The product name that this plugin is part of
[assembly: AssemblyProduct("NightFront")]
[assembly: AssemblyCopyright("Copyright © 2026 Jeff Ridder")]

// The minimum Version of N.I.N.A. that this plugin is compatible with
[assembly: AssemblyMetadata("MinimumApplicationVersion", "3.0.0.2017")]

// The license your plugin code is using
[assembly: AssemblyMetadata("License", "MPL-2.0")]
// The url to the license
[assembly: AssemblyMetadata("LicenseURL", "https://www.mozilla.org/en-US/MPL/2.0/")]
// The repository where your pluggin is hosted
[assembly: AssemblyMetadata("Repository", "https://github.com/jpr86/NightFront-nina-plugin")]

// The following attributes are optional for the official manifest meta data

//[Optional] Your plugin homepage URL - omit if not applicaple
[assembly: AssemblyMetadata("Homepage", "https://github.com/jpr86/NightFront-nina-plugin")]

//[Optional] Common tags that quickly describe your plugin
[assembly: AssemblyMetadata("Tags", "NightFront,Sequencer,Automation,Scheduling")]

//[Optional] A link that will show a log of all changes in between your plugin's versions
[assembly: AssemblyMetadata("ChangelogURL", "https://github.com/jpr86/NightFront-nina-plugin/blob/master/CHANGELOG.md")]

//[Optional] The url to a featured logo that will be displayed in the plugin list next to the name
[assembly: AssemblyMetadata("FeaturedImageURL", "https://raw.githubusercontent.com/jpr86/NightFront-nina-plugin/master/Resources/NightFrontIcon.png")]
//[Optional] A url to an example screenshot of your plugin in action
[assembly: AssemblyMetadata("ScreenshotURL", "")]
//[Optional] An additional url to an example example screenshot of your plugin in action
[assembly: AssemblyMetadata("AltScreenshotURL", "")]
//[Optional] An in-depth description of your plugin
[assembly: AssemblyMetadata("LongDescription", @"NightFront imports nightly imaging plans generated by the NightFront scheduling app (https://github.com/jpr86/NightFront) directly into a NINA Advanced Sequencer sequence.

Add a NightFront Container to your sequence, then place a Nightly Update instruction earlier in the same sequence branch - either as its preceding sibling, or in an ancestor container that runs once before the container is reached (which may itself be nested inside a nightly imaging loop). When the Update instruction runs, it checks the folder configured on this plugin's Options tab for a plan file matching today's date and, if found, populates the NightFront Container with the imported targets, exposures, and filters - ready to run like any other part of your sequence.")]

// Setting ComVisible to false makes the types in this assembly not visible
// to COM components.  If you need to access a type in this assembly from
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// Lets NightFront.Tests exercise internal types directly (e.g. the generated Settings class),
// rather than every test needing a public surface just for testability.
[assembly: InternalsVisibleTo("NightFront.Tests")]
// [Unused]
[assembly: AssemblyConfiguration("")]
// [Unused]
[assembly: AssemblyTrademark("")]
// [Unused]
[assembly: AssemblyCulture("")]